2022-01-01 17:16:17,528 INFO    MainThread:7444 [internal.py:wandb_internal():87] W&B internal server running at pid: 7444, started at: 2022-01-01 17:16:17.527294
2022-01-01 17:16:17,532 INFO    WriterThread:7444 [datastore.py:open_for_write():77] open: C:\university\Thesis\AGAIN-VC - Copy\wandb\offline-run-20220101_171615-18jildpp\run-18jildpp.wandb
2022-01-01 17:16:17,533 DEBUG   HandlerThread:7444 [handler.py:handle_request():130] handle_request: run_start
2022-01-01 17:16:17,560 DEBUG   HandlerThread:7444 [meta.py:__init__():40] meta init
2022-01-01 17:16:17,560 DEBUG   HandlerThread:7444 [meta.py:__init__():54] meta init done
2022-01-01 17:16:17,560 DEBUG   HandlerThread:7444 [meta.py:probe():214] probe
2022-01-01 17:16:17,591 DEBUG   HandlerThread:7444 [meta.py:_setup_git():204] setup git
2022-01-01 17:16:17,795 DEBUG   HandlerThread:7444 [meta.py:_setup_git():211] setup git done
2022-01-01 17:16:17,795 DEBUG   HandlerThread:7444 [meta.py:_save_pip():58] save pip
2022-01-01 17:16:17,796 DEBUG   HandlerThread:7444 [meta.py:_save_pip():72] save pip done
2022-01-01 17:16:17,797 DEBUG   HandlerThread:7444 [meta.py:probe():252] probe done
2022-01-01 17:17:05,825 WARNING MainThread:7444 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-01 17:17:06,174 WARNING MainThread:7444 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-01-01 17:17:06,185 ERROR   MainThread:7444 [internal.py:wandb_internal():149] Internal process interrupted.
2022-01-01 17:17:07,002 INFO    WriterThread:7444 [datastore.py:close():281] close: C:\university\Thesis\AGAIN-VC - Copy\wandb\offline-run-20220101_171615-18jildpp\run-18jildpp.wandb
2022-01-01 17:17:07,002 INFO    HandlerThread:7444 [handler.py:finish():731] shutting down handler
2022-01-01 17:17:07,002 INFO    SenderThread:7444 [sender.py:finish():1070] shutting down sender
2022-01-01 17:17:07,002 INFO    MainThread:7444 [internal.py:handle_exit():77] Internal process exited
